trigger:
  branches:
    include:
      - master

variables:
  - group: KeystoreVariableGroup

pool:
  vmImage: 'windows-latest'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: DownloadSecureFile@1
    displayName: 'Download Keystore File'
    inputs:
      secureFile: 'upload-keystore.jks'
    name: keystore

  - script: |
      echo "Setting up keystore properties"
      echo "storePassword=${KEYSTORE_PASSWORD}" >> $(Build.SourcesDirectory)/keystore.properties
      echo "keyPassword=${KEY_PASSWORD}" >> $(Build.SourcesDirectory)/keystore.properties
      echo "keyAlias=${KEY_ALIAS}" >> $(Build.SourcesDirectory)/keystore.properties
    displayName: 'Setup Keystore Properties'

  - task: Gradle@3
    displayName: 'Build and Sign'
    inputs:
      workingDirectory: '$(Build.SourcesDirectory)'
      gradleWrapperFile: 'gradlew'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean build'

  - script: |
      echo "Creating AAB and mapping.txt files"
      cp $(Build.SourcesDirectory)/app/build/outputs/bundle/release/app-release.aab $(Build.ArtifactStagingDirectory)/app.aab
      cp $(Build.SourcesDirectory)/app/build/outputs/mapping/release/mapping.txt $(Build.ArtifactStagingDirectory)/mapping.txt
    displayName: 'Copy AAB and mapping.txt files'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'BuildArtifacts'
      publishLocation: 'Container'